add typography Title.tsx and Text.tsx
NovaDevelopersCo/nova-learn-landing pull request #19
Opened 2024-01-28 15:42 UTC by TurgunovAmir07

![image](https://github.com/NovaDevelopersCo/nova-learn-landing/assets/144470347/2ca601cf-3819-40aa-8982-7834c5d28760)
![image](https://github.com/NovaDevelopersCo/nova-learn-landing/assets/144470347/70d6a1d4-affa-485a-9ade-5ea8c7b79afc)

2024-01-29 04:30 UTC, EduardDE7 requested changes

2024-01-29 04:30 UTC, EduardDE7 commented on src/components/ui/typography/Text.tsx
add nunito font, leading in px, remove  type className -  any, use in props className || ''

2024-01-29 04:30 UTC, EduardDE7 commented on src/components/ui/typography/Title.tsx
add monserat font, remove size, size written together in the variant, add leading, remove type className - any, use in props className || ''

2024-01-29 04:30 UTC, EduardDE7 commented on tailwind.config.ts
remove font config

2024-01-29 04:30 UTC, EduardDE7 commented on src/app/layout.tsx
remove inter

2024-01-29 04:30 UTC, EduardDE7 commented on src/app/globals.css
remove inter, only 2 fonts

2024-01-30 04:40 UTC, EduardDE7 submitted a review, later dismissed

2024-01-30 04:43 UTC, EduardDE7 approved these changes

2024-01-30 05:42 UTC, coldnanee approved these changes

2024-01-30 05:42 UTC, merged